services:
  localstack:
    image: localstack/localstack:3.2
    container_name: atlasflow-localstack
    ports:
      - "4566:4566"   # LocalStack edge port
      - "4510-4559:4510-4559" # ports for individual services 
    environment:
      - DEBUG=0
      - PERSISTENCE=1
      - SERVICES=s3,sqs,sns,dynamodb,lambda,iam,logs,cloudwatch,ssm,sts
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 30
  api:
    build:
      context: ./api
    container_name: atlasflow-api
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}
      - TF_VAR_project_name=${TF_VAR_project_name:-atlasflow}
      - PROJECT_NAME=atlasflow
      - EVENTS_QUEUE_NAME=${TF_VAR_project_name:-atlasflow}-events
      - EVENTS_TABLE=${TF_VAR_project_name:-atlasflow}-events
      - IDEMPOTENCY_TABLE=${TF_VAR_project_name:-atlasflow}-idempotency
    ports:
      - "8000:8000"
    depends_on:
      localstack:
        condition: service_healthy
  worker:
    build:
      context: ./worker
    container_name: atlasflow-worker
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}
      - TF_VAR_project_name=${TF_VAR_project_name:-atlasflow}
      - EVENTS_QUEUE_NAME=${TF_VAR_project_name:-atlasflow}-events
      - EVENTS_TABLE=${TF_VAR_project_name:-atlasflow}-events
      - POLL_WAIT_SECONDS=5
      - MAX_MESSAGES=5
      - VISIBILITY_TIMEOUT=30
    depends_on:
      localstack:
        condition: service_healthy